ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';

CREATE DATABASE IF NOT EXISTS debezium_test;

USE debezium_test;

CREATE TABLE IF NOT EXISTS time_test (
    `time_test_id`  BIGINT AUTO_INCREMENT PRIMARY KEY,
    `created_sec`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_sec`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_milli` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_milli` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `created_micro` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_micro` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
